### ISSUE TITLE
Web Manifest

### ISSUE THREAD

**Issue by hiz8** [playrjp/playrjp.github.io#13]
Webアプリ化を押し進めるためmanifest.jsonを設置。

参考:
- [Manifest for a web application](https://w3c.github.io/manifest/)
- [App manifest - App Center | MDN](https://developer.mozilla.org/en-US/Apps/Build/Manifest)

MDNにも記事があるし、普段使いのFirefoxでもしっかり動くのだろうか。

**Comment by hiz8** [comment]
モバイルフレンドリーの目線でWebアプリ化に幅広く言及している記事。
- [Service Worker で作る 最新モバイル ウェブ エクスペリエンス - Google Developers Summit まとめ ](http://googledevjp.blogspot.jp/2015/04/service-worker-google-developers-summit.html)

manifest.json

``` json
{
  "name": "Kinlan's Amazing Application ++",
  "short_name": "Kinlan's Amaze App",
  "icons": [
    {
      "src": "launcher-icon-3x.png",
      "sizes": "144x144",
      "type": "image/png"
    }
  ],
  "start_url": "index.html",
  "display": "standalone"
}
```

index.html

``` html
<link rel="manifest" href="/manifest.json">
```

**Comment by hiz8** [comment]
Service Workerを使用した「ホームへ追加」バナーの表示。
- [manifest.json でWebアプリを「ホーム画面に追加」自動バナー表示に対応させる](http://qiita.com/tmtysk/items/2c5da83feec45b4ee36f)

``` javascript
window.addEventListener('load', function() {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js');
  }
});
```

**Comment by hiz8** [comment]
theme-colorの設定
- [Using the web app manifest to specify a site wide theme colour](https://developers.google.com/web/updates/2015/09/using-manifest-to-set-sitewide-theme-color)

metaタグだと

``` html
<meta name="theme-color" content="#2196F3">
```

manifest.jsonだと

``` json
"theme_color": "#2196F3"
```

**Comment by hiz8** [comment]
Service Workerを詳介しているHTML5 Rocksの翻訳記事。
- [Service Worker の紹介](http://www.html5rocks.com/ja/tutorials/service-worker/introduction/)

デバックの手法などにも触れており実践的。

**Comment by hiz8** [comment]
インストールバナーについて詳しく解説している記事

[Increasing engagement with Web App install banners — Google Web Updates](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android)

そのサンプル

[samples/app-install-banner at gh-pages · GoogleChrome/samples](https://github.com/GoogleChrome/samples/tree/gh-pages/app-install-banner)

**Comment by hiz8** [comment]
FirefoxでServiceWorkerをテストする。

`about:config`で`dom.serviceWorkers`を検索し、フラグを`true`へ変更する。

**Comment by hirofumi1987** [comment]
FirefoxでServiceWorkerをテストする。

`about:config`で`dom.serviceWorkers`を検索し、フラグを`true`へ変更する。

**Comment by hiz8** [comment]
[Webアプリをネイティブアプリっぽく起動するWebApp Manifest - Coding Design's Tumblr](http://moonglows76.tumblr.com/post/102930578463/web%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3%E3%83%96%E3%82%A2%E3%83%97%E3%83%AA%E3%81%A3%E3%81%BD%E3%81%8F%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8Bwebapp-manifest)
