### ISSUE TITLE
Error: The `libsass` binding was not found

### ISSUE THREAD

**Issue by hiz8** [playrjp/playrjp.github.io#77]
GulpでSassのコンパイル実行時にエラーが出た。

``` bash
Error: The libsass binding was not found in /node_modules\node-sass\vendor\win32-x64-47\binding.node
```

node-sass内を除いてみるとvendorフォルダが存在しない。
解決策は下記issueで見つけた。
- [node 4.0.0 - Error: The libsass binding was not found in /node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node · Issue #1162 · sass/node-sass](https://github.com/sass/node-sass/issues/1162)

‘npm rebuild node-sass` を実行するとモジュールが再構築され、vendorが配置された。

node-sassはちょくちょく問題を起こす。

**Comment by zoechi** [comment]
I had to rename

`node_modules/node-sass/vendor/linux-x64-` 
to
`node_modules/node-sass/vendor/linux-x64-46`

> node: 4.3.0
> node-sass: ^3.4.2

**Comment by hiz8** [comment]
@zoechi Oh, Thanks!
